### ISSUE TITLE
能使用*来代替所以问题吗, 如let g:auto_striptab = "*"

### ISSUE THREAD

**Issue by fengqi** [dongweiming/vary.vim#1]
因为我可能会编辑css,js,html,php,c,python,go...

**Comment by fengqi** [comment]
嗯 甚至一些配置文件啊什么的

**Comment by dongweiming** [comment]
我个人建议里历数各种后缀.我这里主要还需要设置tab转化成空格的个数,主要是以python代码为主.假如你确定任何文件都这样你可以直接在.vimrc添加类似的配置:

```
autocmd BufWritePre * :%s/\s\+$//e
```

简单粗暴

**Comment by fengqi** [comment]
太除暴了, 也会导致跳到别的行...
